steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [build, -t, corebot.dev, .]

# unit tests
- name: 'gcr.io/cloud-builders/docker'
  args: [run, corebot.dev, dotnet, test, /CoreBot.Test]

- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -f
    - Dockerfile.prod
    - -t
    - gcr.io/eminent-wording-203018/corebot
    - .

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - compute
    - instances
    - reset
    - --zone
    - us-central1-a
    - corebot

images: ['gcr.io/eminent-wording-203018/corebot']
