version: '3'

services:
  corebot:
    container_name: corebot
    build: .
    volumes:
     - ./CoreBot:/app/CoreBot
     - ./CoreBot.Test:/app/CoreBot.Test
     - /app/CoreBot/bin
     - /app/CoreBot.Test/bin
     - /app/CoreBot/obj
     - /app/CoreBot.Test/obj
